#+TITLE: Emacs Starter Kit
#+SEQ_TODO: PROPOSED TODO STARTED | DONE DEFERRED REJECTED
#+OPTIONS: H:2 num:nil toc:t
#+STARTUP: oddeven

#+begin_quote 
Emacs outshines all other editing software in approximately the same
way that the noonday sun does the stars. It is not just bigger and
brighter; it simply makes everything else vanish.

-- Neal Stephenson, "In the Beginning was the Command Line"
#+end_quote

* Introduction
  :PROPERTIES:
  :CUSTOM_ID: introduction
  :END:

This should provide a saner set of defaults than you get normally with
Emacs. It's intended for beginners, but provides a good elisp
initialization structure for all levels of users.

The main advantage of this Emacs Starter Kit are
- better default settings
- inclusion of many useful libraries
- "literate" customization embedded in Org-mode files
- an organizational directory structure
- git provides for version control, backup, and sharing

The latest version is at http://github.com/eschulte/emacs-starter-kit/

** Learning
   :PROPERTIES:
   :CUSTOM_ID: learning
   :END:

This won't teach you Emacs, but it'll make it easier to get
comfortable. To access the tutorial, press control-h followed by t.

The [[http://emacswiki.org][Emacs Wiki]] is also very handy.

** Installation
   :PROPERTIES:
   :CUSTOM_ID: installation
   :END:

1. Install Emacs (at least version 22) Use your package manager if you
   have one.  Otherwise, Mac users should get it [[http://www.apple.com/downloads/macosx/unix_open_source/carbonemacspackage.html][from Apple]], or
   install it directly from [[http://savannah.gnu.org/projects/emacs/][from source]] following the instructions in
   =nextstep/INSTALL=.  Windows users can get it [[http://ftp.gnu.org/gnu/emacs/windows/emacs-22.3-bin-i386.zip][from GNU]].
2. Checkout a version of the starter kit using git -- if you're new to
   git checkout this [[http://www.kernel.org/pub/software/scm/git/docs/gittutorial.html][git-tutorial]], also we'd highly recommend that you
   try out [[http://zagadka.vm.bytemark.co.uk/magit/magit.html][magit]] the Emacs mode for git interaction which comes
   bundled in the starter kit.
   #+begin_src sh
     git clone http://github.com/eschulte/emacs-starter-kit.git
   #+end_src
3. Move the resulting directory to =~/.emacs.d= [1]
4. Install the Org-mode [[http://www.kernel.org/pub/software/scm/git/docs/user-manual.html#submodules][submodules]] with the following
   #+begin_src sh
   cd ~/.emacs.d/
   git submodule init
   git submodule update
   #+end_src
5. build Org-mode
   #+begin_src sh
   cd src/org/
   make
   #+end_src
6. build [[http://www.gnu.org/software/auctex/][auctex]] -- for instilllation help see the [[http://www.gnu.org/software/auctex/manual/auctex/Installation.html#Installation][auctex instillation
   instructions]], auctex requires a working TeX installation
   #+begin_src sh
   cd src/auctex
   ./configure && make
   #+end_src
7. Launch Emacs!

After setup you may need to restart Emacs a couple of times while it
downloads packages from [[* Emacs Lisp Package Archive][ELPA]] -- errors parsing html from
=*tromey.com:80*= can generally be safely ignored.

If you are missing some autoloads after an update (should manifest
itself as "void function: foobar" errors) try M-x regen-autoloads.

If you want to keep your regular ~/.emacs.d in place and just launch a
single instance using the starter kit, try the following invocation:

#+begin_src sh
  emacs -q -l ~/src/emacs-starter-kit/init.el
#+end_src

Note that having a ~/.emacs file might override the starter kit
loading, so if you've having trouble loading it, make sure that file
is not present.

** Structure
   :PROPERTIES:
   :CUSTOM_ID: structure
   :END:

The init.el file is where everything begins. It's the first file to
get loaded. Additional customization embedded in this file provides
what I consider to be better defaults, both for different programming
languages and for built-in Emacs features like bindings or registers.

There are also a few files that are meant for code that doesn't belong
in the Starter Kit, they are described below in [[* customization][Customization]].

** Customization
   :PROPERTIES:
   :CUSTOM_ID: customization
   :END:

The many defaults built into the starter kit are only the beginning of
most users customization of Emacs to suite their needs.  The starter
kit provides a number of places for additional user and system
specific customization.  These are designed in such a way that it will
be easy for you to continue tracking your own personal customization
inside the starter-kit while retaining your ability to pull down
general starter-kit updates without conflict.

- =git branch= :: The first step to user-specific customization is (like
     in any git project) to MAKE A BRANCH FOR YOUR LOCAL CHANGES.
     Save the master branch for pulling down new versions of the
     starter kit, and save all of your personal information in a
     personal branch.  That way you never have to worry about
     accidentally =git push='ing up a patch with all of your gnus
     email passwords.

- User specific config :: Your personal configuration information can
     be stored in a user-specific-config file.  This is the file named
     after your user with the extensions =.el= or =.org= [2].  If
     you're unsure of your user name evaluate the following code block
     to find out.
     #+begin_src sh
       echo $USER
     #+end_src
       
     If your configuration starts to feel cramped in a single file
     (although with the nested headlines of an Org-mode file, that
     could take a while) and you want to stretch your config's legs,
     you can also create a directory named after your system user
     name.  If a such a directory exists, it will be added to the
     load-path, and any elisp or org-mode w/embedded elisp files in it
     will be loaded.

- System specific config :: Finally, you may want to configure
     different settings for different machines.  The Starter Kit will
     look for a file named after the current hostname ending in =.el=
     or =.org= which will allow host-specific configuration.  If
     you're unsure of your hostname the following can be executed to
     find out.
     #+begin_src sh
       hostname
     #+end_src

- Installing more elisp libraries :: While the starter kit include
     many useful Emacs lisp libraries, you are bound to find more that
     you will want to install.  The easiest way to install new
     libraries is through the Emacs Lisp Package Archive (see [[* elpa][ELPA]]).
     When a library is not available through ELPA you can grab it's
     source and place it directly in the =src= directory.  Any
     packages found there will automatically be added to your
     load-path when Emacs starts up, and are guaranteed not to
     conflict with future starter-kit updates.
     
Some additional miscellaneous configuration and getting started
suggestions
- First off see the [[http://www.gnu.org/software/emacs/manual/html_node/emacs/Customization.html#Customization][Customization]] node in the Emacs manual.  Available
  online or through the =info= command (run with =C-h i=).
- =grep='ing through the =starter-kit-*= files in this directory can
  provide useful examples for how to do things like install major
  modes, define keybindings, etc..
- read the following [[http://www.gnu.org/software/emacs/elisp/html_node/Key-Binding-Conventions.html][Key-Binding-Conventions]] before defining too many
  personal key bindings
- The starter-kit comes pre-bundled with a variety of color themes.
  See [[file:starter-kit-misc.org::*Color%20Themes][Color Themes]] for instructions on how to change the colors used
  by Emacs.

** Emacs Lisp Package Archive
   :PROPERTIES:
   :CUSTOM_ID: elpa
   :END:

Libraries from [[http://tromey.com/elpa][ELPA]] are preferred when available since dependencies
are handled automatically, and the burden to update them is removed
from the user. In the long term, ideally everything would be installed
via ELPA, and only [[file:package.el][package.el]] would need to be distributed with the
starter kit. (Or better yet, [[file:package.el][package.el]] would come with Emacs...) See
[[* Starter Kit
 ELPA][Starter Kit ELPA]] for a list of libraries that are pending submission
to ELPA. Packages get installed in the [[file:elpa/][elpa/]] directory.

There's no vendor/ directory in the starter kit because if an external
library is useful enough to be bundled with the starter kit, it should
be useful enough to submit to ELPA so that everyone can use it, not
just users of the starter kit.  However any packages included in the
[[file:src][src/]] directory will be added to the load-path, for tracking bleeding
edge packages.

Sometimes packages are removed from the Starter Kit as they get added
to ELPA itself. This has occasionally caused problems with certain
packages. If you run into problems with such a package, try removing
everything from inside the elpa/ directory and invoking M-x
starter-kit-elpa-install in a fresh instance.

** Contributing
   :PROPERTIES:
   :CUSTOM_ID: contributing
   :END:

If you know your way around Emacs, please try out the starter kit as a
replacement for your regular dotfiles for a while. If there's anything
you just can't live without, add it or let me know so I can add
it. Take a look at what happens in [[file:init.el][init.el]] to get started.

Also: see the [[* Tasks][Tasks section]] in this document. Helping submit new
libraries to ELPA is the easiest way to help out.  There are details
at http://tromey.com/elpa/upload.html for how ELPA submission
works. Grep the project for TODO for other things.

Files are licensed under the same license as Emacs unless otherwise
specified. See the file COPYING for details.

The latest version is at http://github.com/technomancy/emacs-starter-kit/

On Unix, =/home/$USER/.emacs.d=, on windows =Documents and
Settings/%your user name%/Application Data=


* Implementation
  :PROPERTIES:
  :CUSTOM_ID: implementation
  :END:
This section contains all code implementing the Emacs Starter Kit.

** Starter kit basics
*** Load path etc.
#+srcname: starter-kit-load-paths
#+begin_src emacs-lisp 
  (add-to-list 'load-path starter-kit-dir)
  (setq autoload-file (concat starter-kit-dir "loaddefs.el"))
  (setq package-user-dir (concat starter-kit-dir "elpa"))
  (setq custom-file (concat starter-kit-dir "custom.el"))
#+end_src

*** Default ELPA Packages
A few packages should always be installed from ELPA.
#+begin_src emacs-lisp
  (defvar starter-kit-packages
    (list 'yasnippet-bundle 'color-theme)
    "Libraries that should be installed by default.")
  
  (when (and (functionp 'network-interface-list)
             (network-interface-list)
             (some (lambda (iface)
                     (unless (equal "lo" (car iface))
                       (member 'up (first (last (network-interface-info
                                                 (car iface)))))))
                   (network-interface-list)))
    (unless package-archive-contents
      (package-refresh-contents))
    (dolist (package starter-kit-packages)
      (unless (or (member package package-activated-list)
                  (functionp package))
        (message "Installing %s" (symbol-name package))
        (package-install package))))
#+end_src

*** Ubiquitous Packages
These should be loaded on startup rather than autoloaded on demand
since they are likely to be used in every session
#+srcname: starter-kit-load-on-startup
#+begin_src emacs-lisp 
  (require 'cl)
  (require 'saveplace)
  (require 'ffap)
  (require 'uniquify)
  (require 'ansi-color)
  (require 'recentf)
#+end_src

*** Function for loading starter-kit-*
#+srcname: starter-kit-load
#+begin_src emacs-lisp 
  (defun starter-kit-load (file)
    "This function is to be used to load starter-kit-*.org files."
    (org-babel-load-file (expand-file-name file starter-kit-dir)))
#+end_src

*** Work around OS X bug
Work around a bug on OS X where system-name is FQDN
#+srcname: starter-kit-osX-workaround
#+begin_src emacs-lisp 
  (if (eq system-type 'darwin)
      (setq system-name (car (split-string system-name "\\."))))
#+end_src

*** System/User specific customizations
You can keep system- or user-specific customizations here in either
raw emacs-lisp files or as embedded elisp in org-mode files (as done
in this document).

#+srcname: starter-kit-user/system-setup
#+begin_src emacs-lisp 
  (setq
   system-specific-config (concat starter-kit-dir system-name ".el")
   system-specific-literate-config (concat starter-kit-dir system-name ".org")
   user-specific-config (concat starter-kit-dir user-login-name ".el")
   user-specific-literate-config (concat starter-kit-dir user-login-name ".org")
   user-specific-dir (concat starter-kit-dir user-login-name))
  (add-to-list 'load-path user-specific-dir)
#+end_src

You can keep elisp source in the =src= directory.  Packages loaded
from here will override those installed by ELPA.  This is useful if
you want to track the development versions of a project, or if a
project is not in elpa.

#+srcname: starter-kit-load-elisp-dir
#+begin_src emacs-lisp
(setq elisp-source-dir (concat starter-kit-dir "src"))
(add-to-list 'load-path elisp-source-dir)
#+end_src

** Load the rest of the starter kit core
The following files contain the remainder of the core of the Emacs
Starter Kit.  All of the code in this section should be loaded by
everyone using the starter kit.

*** Starter kit defuns
Starter kit function definitions in [[file:starter-kit-defuns.org][starter-kit-defuns]]

#+begin_src emacs-lisp
(starter-kit-load "starter-kit-defuns.org")
#+end_src

*** Starter kit bindings
Key Bindings in [[file:starter-kit-bindings.org][starter-kit-bindings]]

#+begin_src emacs-lisp
(starter-kit-load "starter-kit-bindings.org")
#+end_src

*** Starter kit misc
Miscellaneous settings in [[file:starter-kit-misc.org][starter-kit-misc]]

#+begin_src emacs-lisp
(starter-kit-load "starter-kit-misc.org")
#+end_src

*** Starter kit registers
Registers for jumping to commonly used files in [[file:starter-kit-registers.org][starter-kit-registers]]

#+begin_src emacs-lisp
(starter-kit-load "starter-kit-registers.org")
#+end_src

** Language/Mode Specific Files
These sections pertain to specific languages or modes.  Feel free to
turn off these sections if you don't plan on using the related mode or
language.

*** Starter kit yasnippet
[[http://code.google.com/p/yasnippet/][yasnippet]] is yet another snippet expansion system for Emacs.  It is
inspired by TextMate's templating syntax.
- watch the [[http://www.youtube.com/watch?v=vOj7btx3ATg][video on YouTube]]
- see the [[http://yasnippet.googlecode.com/svn/trunk/doc/index.html][intro and tutorial]]

load the yasnippet bundle
#+begin_src emacs-lisp
  (add-to-list 'load-path
               (expand-file-name  "yasnippet"
                                  (expand-file-name "src"
                                                    starter-kit-dir)))
  (require 'yasnippet)
  (yas/initialize)
#+end_src

load the snippets defined in the =./snippets/= directory
#+begin_src emacs-lisp
  (yas/load-directory (expand-file-name "snippets" starter-kit-dir))
#+end_src

*** Starter kit Org-mode
Located in [[file:starter-kit-org.org][starter-kit-org]]

#+begin_src emacs-lisp
(starter-kit-load "starter-kit-org.org")
#+end_src

*** Starter kit eshell
Located in [[file:starter-kit-eshell.org][starter-kit-eshell]]

#+begin_src emacs-lisp
(starter-kit-load "starter-kit-eshell.org")
#+end_src

*** Starter kit lisp
Located in [[file:starter-kit-lisp.org][starter-kit-lisp]]

#+begin_src emacs-lisp
(starter-kit-load "starter-kit-lisp.org")
#+end_src

*** Starter kit Haskell
Located in [[file:starter-kit-haskell.org][starter-kit-haskell]]

#+begin_src emacs-lisp
(starter-kit-load "starter-kit-haskell.org")
#+end_src

*** Starter kit ruby
Located in [[file:starter-kit-ruby.org][starter-kit-ruby]]

#+begin_src emacs-lisp
(starter-kit-load "starter-kit-ruby.org")
#+end_src

*** Starter kit JS
Located in [[file:starter-kit-js.org][starter-kit-js]]

#+begin_src emacs-lisp
(starter-kit-load "starter-kit-js.org")
#+end_src

*** Starter Kit Perl
Located in [[file:starter-kit-perl.org][starter-kit-perl]]

#+begin_src emacs-lisp
(starter-kit-load "starter-kit-perl.org")
#+end_src

*** Starter Kit Python
Located in [[file:starter-kit-python.org][starter-kit-python]]

#+begin_src emacs-lisp
(starter-kit-load "starter-kit-python.org")
#+end_src

*** Starter Kit Latex
Located in [[file:starter-kit-latex.org][starter-kit-latex]]

#+begin_src emacs-lisp
;; (starter-kit-load "starter-kit-latex.org")
#+end_src

** Load User/System Specific Files
*** Settings from M-x customize
#+srcname: m-x-customize-customizations
#+begin_src emacs-lisp 
  (load custom-file 'noerror)
#+end_src

*** E-lisp customization
After we've loaded all the Starter Kit defaults, lets load the User's stuff.
#+srcname: starter-kit-load-files
#+begin_src emacs-lisp
  (if (file-exists-p elisp-source-dir)
      (let ((default-directory elisp-source-dir))
        (normal-top-level-add-subdirs-to-load-path)))
  (if (file-exists-p system-specific-config) (load system-specific-config))
  (if (file-exists-p system-specific-literate-config)
      (org-babel-load-file system-specific-literate-config))
  (if (file-exists-p user-specific-config) (load user-specific-config))
  (if (file-exists-p user-specific-literate-config)
      (org-babel-load-file user-specific-literate-config))
  (when (file-exists-p user-specific-dir)
    (let ((default-directory user-specific-dir))
      (mapc #'load (directory-files user-specific-dir nil ".*el$"))
      (mapc #'org-babel-load-file (directory-files user-specific-dir nil ".*org$"))))
#+end_src


* FAQ
  :PROPERTIES:
  :tangle:   no
  :END:
Frequently asked questions.

Please share anything that you have come across which you think could
be helpful, either in the form of a pull request, a patch, or just an
email to me http://github.com/eschulte.



* Footnotes

[1] If you already have a directory at ~/.emacs.d move it out of
the way and put this there instead.

[2] The emacs starter kit uses [[http://orgmode.org/worg/org-contrib/babel/][org-babel]] to load embedded elisp code
directly from [[http://orgmode.org/][Org Mode]] documents.

