#+TITLE: Starter Kit Yasnippet
#+OPTIONS: toc:nil num:nil ^:nil

This is part of the [[file:starter-kit.org][Emacs Starter Kit]].

* Starter Kit Yasnippet
[[http://code.google.com/p/yasnippet/][yasnippet]] is yet another snippet expansion system for Emacs.  It is
inspired by TextMate's templating syntax.
- watch the [[http://www.youtube.com/watch?v=vOj7btx3ATg][video on YouTube]]
- see the [[http://yasnippet.googlecode.com/svn/trunk/doc/index.html][intro and tutorial]]

** Install Yasnippet
   :PROPERTIES:
   :CUSTOM_ID: install
   :END:
#+begin_src emacs-lisp
  (starter-kit-install-if-needed 'yasnippet)

  ;; If `yasnippet-bundle' has previously been installed through ELPA,
  ;; delete it before installing the new `yasnippet'
  (let ((yas-bundle-desc (assq 'yasnippet-bundle package-alist)))
    (when yas-bundle-desc
      (package-delete "yasnippet-bundle"
                      (package-version-join
                       (package-desc-vers (cdr yas-bundle-desc))))))
#+end_src

** Put yasnippet directories on the load path
   :PROPERTIES:
   :CUSTOM_ID: snippet-paths
   :END:
#+begin_src emacs-lisp
  (add-to-list 'load-path
               (expand-file-name  "yasnippet"
                                  (expand-file-name "src"
                                                    starter-kit-dir)))
#+end_src

** Load Yasnippet
   :PROPERTIES:
   :CUSTOM_ID: load
   :END:
#+begin_src emacs-lisp
  (require 'yasnippet)
  (yas-global-mode 1)
#+end_src

** Load Snippets Distributed with the Starter Kit
   :PROPERTIES:
   :CUSTOM_ID: default-snippets
   :END:
Load the snippets defined in the =./snippets/= directory.
#+begin_src emacs-lisp
  (yas/load-directory (expand-file-name "snippets" starter-kit-dir))
#+end_src

** Configure Yasnippets for Org Mode
   :PROPERTIES:
   :CUSTOM_ID: org-mode
   :END:

The latest version of yasnippets doesn't play well with Org-mode, the
following function allows these two to play nicely together.
#+begin_src emacs-lisp
  (defun yas/org-very-safe-expand ()
    (let ((yas/fallback-behavior 'return-nil)) (yas/expand)))

  (defun yas/org-setup ()
    ;; yasnippet (using the new org-cycle hooks)
    (make-variable-buffer-local 'yas/trigger-key)
    (setq yas/trigger-key [tab])
    (add-to-list 'org-tab-first-hook 'yas/org-very-safe-expand)
    (define-key yas/keymap [tab] 'yas/next-field))

  ;; See https://github.com/eschulte/emacs24-starter-kit/issues/80.
  (setq org-src-tab-acts-natively nil)

  (add-hook 'org-mode-hook #'yas/org-setup)
#+end_src
